// utils/skillIconMap.ts
import {
    SiDocker,
    SiKubernetes,
    SiJenkins,
    SiTerraform,
    SiMicrosoftazure,
    SiGit,
    SiReact,
    SiNextdotjs,
    SiTailwindcss,
    // SiAmazonaws,
    SiNodedotjs,
    SiExpress,
    SiMongodb,
    SiPostgresql,
    SiMysql,
    SiRedis,
    SiFirebase,
    SiGraphql,
    SiTypescript,
    SiJavascript,
    SiPrometheus,
    SiLinux,
    SiNginx,
    SiFirebase as SiFirebaseIcon,
} from "react-icons/si";
import { FaTools, FaCloud, FaCodeBranch, FaShieldAlt } from "react-icons/fa";

export const skillIconMap: Record<string, JSX.Element> = {
    Docker: <SiDocker />,
    Kubernetes: <SiKubernetes />,
    Jenkins: <SiJenkins />,
    Terraform: <SiTerraform />,
    Azure: <SiMicrosoftazure />,
    Git: <SiGit />,
    "Full-Stack": <FaTools />,
    "Responsive Design": <FaTools />,
    DevOps: <FaTools />,
    "Cloud Computing": <FaCloud />,
    DSA: <FaCodeBranch />,
    "System Design": <FaCodeBranch />,
    "SEO Optimization": <FaShieldAlt />,
    "React.js": <SiReact />,
    "Next.js": <SiNextdotjs />,
    "Tailwind CSS": <SiTailwindcss />,
    // AWS: <SiAmazonaws />,
    "Node.js": <SiNodedotjs />,
    "Express.js": <SiExpress />,
    Microservices: <FaTools />,
    Linux: <SiLinux />,
    Nginx: <SiNginx />,
    MongoDB: <SiMongodb />,
    PostgreSQL: <SiPostgresql />,
    MySQL: <SiMysql />,
    Redis: <SiRedis />,
    Firebase: <SiFirebaseIcon />,
    GraphQL: <SiGraphql />,
    TypeScript: <SiTypescript />,
    JavaScript: <SiJavascript />,
    APIs: <FaTools />,
    Agile: <FaTools />,
    Scrum: <FaTools />,
    WebSecurity: <FaShieldAlt />,
    "Version Control": <FaCodeBranch />,
    Prometheus: <SiPrometheus />,
    CloudFormation: <FaCloud />,
    IAC: <SiTerraform />,
};
  